# Generated by Django 5.1.7 on 2025-03-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_bouquet_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bouquet',
            name='image_url',
        ),
        migrations.AddField(
            model_name='bouquet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bouquets/', verbose_name='Изображение'),
        ),
    ]
